version: '3'

networks:
    web_pramayasa:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}-nginx
        restart: always
        ports:
            - "${PORT}:80"
        volumes:
            - ./public:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - web_pramayasa

    php:
        build: .
        container_name: ${APP_NAME}-php
        restart: always
        volumes:
            - ./public:/var/www/html
        networks:
            - web_pramayasa
