version: '3'

networks:
    web_2077:

services:
    php:
        restart: always
        environment: 
            APP_ENV: production

    mysql:
        restart: always
        environment:
            SERVICE_TAGS: production

    phpmyadmin:
        environment:
            PMA_HOST: 
            PMA_PORT:
            PMA_DB_SERVER:
            PMA_USER:
            PMA_PASSWORD:
