version: '3'

networks:
    web_2077:

services:
    php:
        build: .
        container_name: ${APP_NAME}-php
        restart: unless-stopped
        environment: 
            APP_ENV: development
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./src:/var/www/html:ro
            - ./flag1.txt:/flag1.txt:ro
            - ./hint.txt:/hint.txt:ro
            - ./custom-php.ini:/usr/local/etc/php/conf.d/custom.php.ini:ro
        networks:
            - web_2077

    mysql:
        image: mysql:5.7.22
        container_name: ${APP_NAME}-mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "${DB_PORT}:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./user.sql:/docker-entrypoint-initdb.d/user.sql:ro
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: a2FzZGoxMjk4N2R5NzhuZHNpamZoamhld2lmdTg
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - web_2077

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}-phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: ${DB_PORT}
            PMA_DB_SERVER: mysql
            PMA_USER: root
            PMA_PASSWORD: a2FzZGoxMjk4N2R5NzhuZHNpamZoamhld2lmdTg
        ports:
            - "8081:80"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - web_2077

volumes: 
    dbdata: {} 
