version: '3'

networks:
    web_2077:

services:
    php:
        build: .
        container_name: ${APP_NAME}-php
        restart: always
        environment: 
            APP_ENV: production
        ports:
            - "${PORT}:80"
        volumes:
            - ./src:/var/www/html:ro
            - ./hint2.txt:/hint2.txt:ro
        networks:
            - web_2077

    mysql:
        image: mysql:5.7.22
        container_name: ${APP_NAME}-mysql
        restart: always
        tty: true
        ports: 
            - "2087:3306"
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${APP_NAME}
            MYSQL_USER: s3cr3T_Us3r
            MYSQL_PASSWORD: s3cr3t_p4s5w0rd
            MYSQL_ROOT_PASSWORD: a2FzZGoxMjk4N2R5NzhuZHNpamZoamhld2lmdTg
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - web_2077

volumes: 
    dbdata: {} 
