version: '2'
services:
  babypwn:
    image: babypwn
    build: .
    restart: always
    environment:
      - TERM=xterm
    ports:
      - '30203:30203'
    volumes:
      - ./chall:/home/babypwn/chall:ro
      - ./flag.txt:/home/babypwn/flag.txt:ro
      - ./xinetd:/etc/xinetd.d/babypwn:ro
      - ./startchall.sh:/home/babypwn/startchall:ro
