version: '2'
services:
  babyheap:
    image: babyheap
    build: .
    restart: always
    environment:
      - TERM=xterm
    ports:
      - '1337:1337'
    volumes:
      - ./babyheap:/home/babyheap/babyheap:ro
      - ./flag.txt:/home/babyheap/flag.txt:ro
      - ./xinetd:/etc/xinetd.d/babyheap:ro
      - ./startchall.sh:/home/babyheap/startchall:ro
